### ISSUE TITLE
chatrender failing - System.ArgumentNullException: Value cannot be null. (Parameter 'asset')

### ISSUE THREAD

**Issue by nguyend24** [Zibbp/ganymede#164]
Making a new issue since it's unrelated to #153 

Reported here https://github.com/Zibbp/ganymede/issues/153#issuecomment-1496927026, it works after running `fc-cache -f`, that was with running TwitchDownloaderCLI as `root`.

It failed again in the same way when trying to rerun Chat Render in the WebUI. 

`abc` user was unable to `cd` into any folders in /usr/share/fonts. `ls` showed the files, but gave permission denied errors.

According to this, execute is also needed, not just read. https://serverfault.com/questions/283405/permission-denied-to-cd-into-a-directory-even-though-permissions-are-correct

Added execute permissions to /usr/share/fonts/* with `root`. Ran `fc-cache -f` and Chat Render in the WebUI and on CLI for `abc` user now works.

Worked on videos that previously had this error. And new livestreams.

Some chats still fail without an error though. Related to #68. Still trying to figure that one out.

**Comment by Zibbp** [comment]
Thanks for looking into the issue, I pushed some changes in https://github.com/Zibbp/ganymede/commit/44d63977359ced1869f2157ec33b2ea8597db2c9 which sets the fonts to be executable in the Dockerfile and on boot, run `fc-cache -f` as the `abc` user.
https://github.com/Zibbp/ganymede/blob/44d63977359ced1869f2157ec33b2ea8597db2c9/Dockerfile#L44

https://github.com/Zibbp/ganymede/blob/44d63977359ced1869f2157ec33b2ea8597db2c9/entrypoint.sh#L24

If you wish to try, pull the `:main` tag.

> Some chats still fail without an error though. Related to https://github.com/Zibbp/ganymede/issues/68. Still trying to figure that one out.

Feel free to upload a problematic chat file and I can take a look.

**Comment by nguyend24** [comment]
Thanks! It works with the latest version.

> Feel free to upload a problematic chat file and I can take a look.
Still can't reliably reproduce. Usually rerunning the render works. Managed to get it to seg fault once outside ganymede. Will provide an update if I can pinpoint it.

**Comment by Zibbp** [comment]
Perfect, I'll push out a new release with this fix so it will be available on the `:latest` tag.
