### ISSUE TITLE
Chat rendering fails with no error

### ISSUE THREAD

**Issue by Keagel** [Zibbp/ganymede#68]
Hello!

Back with another issue. Sometimes chat rendering will fail with no error. Checking the logs the last lines are just the current status of rendering.

```
[STATUS] - Rendering Video 34% (4h11m41s left)
[STATUS] - Rendering Video 34% (4h11m41s left)
[STATUS] - Rendering Video 34% (4h11m41s left)
```

I don't see any debug logging options for TwitchDownloaderCLI so I'm not sure how to find out what actually causes the process to stop.

**Comment by Zibbp** [comment]
Hi,
Usually if it fails, it providers an error, at least in my experience. Is there a chance that you're running out of disk space?

TwitchDownloader recently had some large updates so I will test those soon and push it up to Ganymede, maybe that will fix something.

**Comment by Keagel** [comment]
>  Usually if it fails, it providers an error, at least in my experience. Is there a chance that you're running out of disk space?

Unfortunately no, I have plenty of disk space so that's not it.

**Comment by Zibbp** [comment]
Does this happen to specific VODs or randomly when rendering?

**Comment by Keagel** [comment]
It's pretty random. Usually I run it again and it works fine.

**Comment by Zibbp** [comment]
I found an issue in the TwitchDownloader repo with perhaps a similar issue https://github.com/lay295/TwitchDownloader/issues/469. I'm not sure if it's the issue you have having but the fix was published in the latest release.

I just published [v1.1.2](https://github.com/Zibbp/ganymede/releases/tag/v1.1.2) which includes the latest TwitchDownloader version. When you have no active queue items, pull down the latest container and give it a try.

**Comment by Keagel** [comment]
Unfortunately it still occurs. I'm going to try and find a way to monitor the processes to find out why they stop as it doesn't seem like they're hanging.

**Comment by Zibbp** [comment]
I might have encountered the same issue last night while rendering the chat for a VOD. It seemed to stop output in the logs, and sent the error notification. I checked the container logs and saw this.
```
2022-12-18T20:47:34-06:00 ERR error running TwitchDownloaderCLI for vod chat render | error=signal: segmentation fault (core dumped)
2022-12-18T20:47:34-06:00 ERR error checking chat render logfile for no messages | error=exit status 1
2022-12-18T20:47:34-06:00 ERR error rendering chat | error=exit status 1
```

I restarted the chat render but it failed again after some time.
I'll have to do some more investigating.

**Comment by Zibbp** [comment]
Hi,
I'm unsure if the issue you were having is related to mine, but I just released a new version which includes a backup font when Inter is not able to render some language's symbols. This was the issue that was causing my chat render to crash.

If you have the "debug" option enabled in `config.json`, can you provide the error that is output from the api-conter logs similar to my above message?

**Comment by Keagel** [comment]
Sorry for the delay! I just pulled the newest changes from git and will let you know how it goes. I can confirm I had the same segmentation fault error you did in the container logs.

**Comment by Keagel** [comment]
Unfortunately the error still occurs.

```
ganymede-api  | {"level":"error","error":"signal: segmentation fault (core dumped)","time":"2023-01-10T14:29:32Z","message":"error running TwitchDownloaderCLI for vod chat render"}
ganymede-api  | {"level":"error","error":"exit status 1","time":"2023-01-10T14:29:32Z","message":"error checking chat render logfile for no messages"}
ganymede-api  | {"level":"error","error":"exit status 1","time":"2023-01-10T14:29:32Z","message":"error rendering chat"}
ganymede-api  | {"level":"error","error":"signal: segmentation fault (core dumped)","time":"2023-01-11T13:13:29Z","message":"error running TwitchDownloaderCLI for vod chat render"}
ganymede-api  | {"level":"error","error":"exit status 1","time":"2023-01-11T13:13:29Z","message":"error checking chat render logfile for no messages"}
ganymede-api  | {"level":"error","error":"exit status 1","time":"2023-01-11T13:13:29Z","message":"error rendering chat"}
```

I ended up trying to run the command directly within the docker container to figure out if I could get more details but got the same error. I thought it might be linked to https://github.com/Zibbp/ganymede/issues/61#issuecomment-1324069710 so I copied the `/usr/share/fonts` directory from the container, put in on the host, changed the permissions and mounted the folder in the container. I ran the same command which kept crashing at the same percentage and this time it succeeded.

**Comment by Zibbp** [comment]
If I remember correctly you are running Ganymede with a different UID correct? That is probably causing permission issues while attempting to read a font, but you're able to render to a certain % so maybe a fallback font?

I'm curious about something. Ganymede ships with a default chat render argument that uses the installed Inter font. Can you remove `--font Inter` from the Chat Render Args at Admin > Settings. This will allow TwitchDownloaderCLI to use the embedded Inter version.

I'm going to guess that there is a chat message that uses a language not supported by Inter which is why it is failing. It wants to use a fallback font but the custom UID you have doesn't have access to those fallback fonts as they are installed as root. This is why when you mount the font folder and change the permissions it works.

I need to cleanup the Dockerfile so it runs better when not using root.

**Comment by Zibbp** [comment]
Are you receiving an error similar to `segmentation fault (core dumped)` in either the API or chat render logs? If you are not using a custom uid in your docker-compose, please open a new issue with the chat json that is having issues and the errors.
